### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by zkoppert** [super-linter/super-linter#4947]
In order to prepare for the v6 release, we need to modify instances of v5 to v6 where they relate to the super linter package version

- [x] https://github.com/super-linter/super-linter/blob/main/slim/README.md?plain=1#L5 Not needed anymore, see #4957
- [x] https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md?plain=1#L109 Not needed anymore, see #4981
- [x] https://github.com/super-linter/super-linter/blob/main/TEMPLATES/linter.yml#L60 Not needed anymore, see #4981
- [ ] https://github.com/super-linter/super-linter/blob/main/slim/action.yml#L7
- [ ] https://github.com/super-linter/super-linter/blob/main/action.yml#L7
- [ ] https://github.com/super-linter/super-linter/blob/main/README.md?plain=1#L183

**Comment by ferrarimarco** [comment]
Thanks for putting this together. Maybe we can document the process?

**Comment by zkoppert** [comment]
Would you prefer it as an issue template/form or as a markdown doc in the repo somewhere?

**Comment by ferrarimarco** [comment]
I guess a markdown doc works? A PR template would be nice, but I don't think we can restrict that to maintainers only?

Also, having this written in a document might help us thinking about how to eventually automate this.

Thanks!

**Comment by ferrarimarco** [comment]
Or shall we tweak the [release workflow](https://github.com/super-linter/super-linter/blob/main/.github/workflows/release.yml) directly, to do this on our behalf?

**Comment by ferrarimarco** [comment]
Relevant action: https://github.com/googleapis/release-please

**Comment by zkoppert** [comment]
Oh that would be cool!!

**Comment by ferrarimarco** [comment]
Other tools:

- https://github.com/semantic-release/semantic-release

**Comment by ferrarimarco** [comment]
To do:

- [ ] #5014 
- [ ] Configure release-please
- [ ] Remove draft-release workflow
- [ ] Remove release workflow
